### ISSUE TITLE
[FEATURE]: Authenticated Request Support

### ISSUE THREAD

**Issue by Morgul** [zS1L3NT/ts-npm-ytmusic-api#12]
### Is this feature request related to a problem? If so, please elaborate

Currently (unless I missed it) there is no way to make authenticated requests. Most other ytm apis have support for a cookies.txt file, or a header string.

### Tell me about the feature you are requesting!

It would be nice to be able to, for example, pull my private playlists because I'm authenticated. There's other features that could be added (playlist creation/manipulation, etc).

### Additional Information

Currently in my little project I have to use two different apis because the other one doesn't have all the same metadata this one has (or it's broken) meanwhile this one doesn't let me access things that require authentication. It would be nice to see this expand so I don't need to use the other one.

**Comment by zS1L3NT** [comment]
I don't mind giving this feature a try. For now, I'm extremely busy so I'll start working on this in August. Pull Requests are welcome tho :D

**Comment by zS1L3NT** [comment]
Version v4.2.0 has been released with this feature, [here](https://ytmusic-api.zectan.com/guides/usage.html#custom-cookies) is a link to the documentation for how to inject your custom cookies

**Comment by jmanaside** [comment]
Hello @zS1L3NT the documentation seems down. was it moved?

**Comment by zS1L3NT** [comment]
Hi, I shut it down because I thought the type definitions and comments for the functions in the code were enough and the website was quite unnecessary
