### ISSUE TITLE
[BUG]: Incorrect Album Information

### ISSUE THREAD

**Issue by 3G64IhRCnLRJXcKiSQdm** [zS1L3NT/ts-npm-ytmusic-api#22]
### Please describe the current behaviour of the code.

It's showing nothing for the albumId and the amount of plays for the name.

### Please describe the expected behaviour of the code.

It should show the albumId and the proper name.

### What are the steps to reproduce the error?

Log the output from getArtist(artistId).topSongs.

### Additional Information

The logged output:

```{type: 'SONG', videoId: '4L56DPmFl8w', name: 'Would?', artists: Array(1), album: {…}, …}
album: {albumId: '', name: '205M plays'}
artists: [{…}]
name: "Would?"
thumbnails: (2) [{…}, {…}]
type: "SONG"
videoId: "4L56DPmFl8w"
[[Prototype]]: Object```

**Comment by zS1L3NT** [comment]
Give me a few days to fix this

**Comment by zS1L3NT** [comment]
What's the query you used to get this bug?

**Comment by 3G64IhRCnLRJXcKiSQdm** [comment]
```let SimilarArtistInfo = await YTMusicAPI.getArtist(ArtistInfo.similarArtists[j].artistId);```

**Comment by zS1L3NT** [comment]
As in the "string" that was passed to get this query result

```js
ytmusic.getArtist("who")
```

**Comment by 3G64IhRCnLRJXcKiSQdm** [comment]
Here's a few, all of them show the same stuff: ["UCGexNm_Kw4rdQjLxmpb2EKw","UCrPe3hLA51968GwxHSZ1llw","UCjtMrcJSQnXyE0rGfQlr8MA"]
Also sorry about the late response, I was busy with something.

**Comment by zS1L3NT** [comment]
I ran some code to test the results I get, none of them gave me anything with `{ albumId: "", name: "* plays" }`... Can you try to run this on your side and tell me which objects have the empty values?

The example you gave at the top shows the song "Would?" having empty values but on my side, "Would?" comes with all values filled properly...

```ts
import YTMusic from "./YTMusic"

const ytmusic = new YTMusic()
ytmusic.initialize().then(() => {
	ytmusic.getArtist("UCGexNm_Kw4rdQjLxmpb2EKw").then(data => Bun.write("UCGexNm_Kw4rdQjLxmpb2EKw.json", JSON.stringify(data, null, 4)))
	ytmusic.getArtist("UCrPe3hLA51968GwxHSZ1llw").then(data => Bun.write("UCrPe3hLA51968GwxHSZ1llw.json", JSON.stringify(data, null, 4)))
	ytmusic.getArtist("UCjtMrcJSQnXyE0rGfQlr8MA").then(data => Bun.write("UCjtMrcJSQnXyE0rGfQlr8MA.json", JSON.stringify(data, null, 4)))
})
```

**Comment by 3G64IhRCnLRJXcKiSQdm** [comment]
I have found the issue, I was using an outdated version of it, I added the latest thing at the end of the npm and it works now, my bad about that.
