### ISSUE TITLE
[FEATURE]: Support languages

### ISSUE THREAD

**Issue by SAROND-DEV** [zS1L3NT/ts-npm-ytmusic-api#23]
### Is this feature request related to a problem? If so, please elaborate

Currently, the content is returned only in English. Youtube Music also supports many other languages

### Tell me about the feature you are requesting!

Add the ability to change the language of the returned content

Example:
```
const ytm = new YTMusic();
await ytm.initialize();
ytm.setLocale('de')
```

### Additional Information

I found out that Youtube Music uses header "Accept-Language" and "hl" for support languages

**Comment by zS1L3NT** [comment]
Why do you need this feature? I don't know how changing the language will affect the responses since the video titles are all fixed and shouldn't change depending on your locale, so I'm not sure how to even implement it and test that it works...

**Comment by SAROND-DEV** [comment]
I noticed that depending on the specified language and/or location, the output of content by the algorithm may change

Example:
Region: GE, Lang: RU
![image](https://github.com/zS1L3NT/ts-npm-ytmusic-api/assets/32885796/d985cf22-69a0-4576-82aa-ac258bdeb20b)

Region: US, Lang: EN
![image](https://github.com/zS1L3NT/ts-npm-ytmusic-api/assets/32885796/dee8abe2-cfca-441f-ab10-e1143e46868c)

**Comment by SAROND-DEV** [comment]
By changing these 2 values alternately, I managed to get a different answer
![image](https://github.com/zS1L3NT/ts-npm-ytmusic-api/assets/32885796/388007e5-75dc-4bd6-ad54-ce0ade3e74e4)

**Comment by zS1L3NT** [comment]
Version v5.1.0 has been released with the ability to change the locale according to what you instructed about changing the `gl` and `hl` values. Could you verify that it works on your side then close this issue? Thanks

**Comment by SAROND-DEV** [comment]
I managed to check it out. And it works great. But sometimes there are problems with parsers when you try to request the main page

**Comment by zS1L3NT** [comment]
Can you give me an example of a code snippet that doesn't work to test on my side?

**Comment by SAROND-DEV** [comment]
I'm not sure if this is a problem with the added feature. Since localization works correctly

Try call method getAlbum with FEmusic_home params (Main page Youtube Music)
```js
const ytm = new YTMusic();
await ytm.initialize({ GL: 'US', HL: 'en' });
ytm.getAlbum('FEmusic_home')
```

**Comment by zS1L3NT** [comment]
Why do you need that? I don't think that's a valid Album ID on YouTube Music...

**Comment by SAROND-DEV** [comment]
I'm closing issue. After a more detailed understanding, it turned out that the problem goes beyond the scope of the requested feature.

P.S
I wanted to get albums, playlists, song and videos using the Youtube Music algorithm, bypassing the search.
`FEmusic_home` - by specifying this parameter we get the same dynamic content as [Youtube Music HomePage](https://music.youtube.com/)
