### ISSUE TITLE
[BUG]: Bump arktype from 1.0.28-alpha to 1.0.29-alpha

### ISSUE THREAD

**Issue by SAROND-DEV** [zS1L3NT/ts-npm-ytmusic-api#25]
### Please describe the current behaviour of the code.

I need a patch that was made for compatibility with sass
https://github.com/arktypeio/arktype/issues/900

### Please describe the expected behaviour of the code.

No answer

### What are the steps to reproduce the error?

No answer

**Comment by zS1L3NT** [comment]
Version v5.0.3 has been released with arktype@1.0.29-alpha
