### ISSUE TITLE
[BUG]: Cookie not in this host's domain. Cookie: www.youtube.com Request: music.youtube.com

### ISSUE THREAD

**Issue by SAROND-DEV** [zS1L3NT/ts-npm-ytmusic-api#28]
### Please describe the current behaviour of the code.

When running the method [setCookieSync](https://github.com/zS1L3NT/ts-npm-ytmusic-api/blob/939ef8f3b16ef0c384ff540bf7c55d115cda2724/src/YTMusic.ts#L73), i getting an error
```
error: Cookie not in this host's domain. Cookie:www.youtube.com Request:music.youtube.com
      at setCookie (/mnt/c/Users/PC/Desktop/projects/ts-npm-ytmusic-api/node_modules/tough-cookie/lib/cookie.js:1194:15)
      at /mnt/c/Users/PC/Desktop/projects/ts-npm-ytmusic-api/node_modules/universalify/index.js:5:64
      at /mnt/c/Users/PC/Desktop/projects/ts-npm-ytmusic-api/node_modules/tough-cookie/lib/cookie.js:1726:5
      at /mnt/c/Users/PC/Desktop/projects/ts-npm-ytmusic-api/src/YTMusic.ts:73:6
      at processTicksAndRejections (:61:77)
```

### Please describe the expected behaviour of the code.

Successful run methods

### What are the steps to reproduce the error?

Try
```js
const ytm = new YTMusic();
await ytm.initialize();
```

**Comment by teleport-1254** [comment]
same issue. 🙂🥲

**Comment by SAROND-DEV** [comment]
I found a simple solution, but I not sure if it the best idea.

```js
cookiejar.setCookieSync(cookie, url, { ignoreError: true })
```

**Comment by zS1L3NT** [comment]
Version v5.2.2 has been released with this bug fixed. I set the cookie url to `www.youtube.com` instead of `music.youtube.com`
