### ISSUE TITLE
Bring back returning the `year` data of an album.

### ISSUE THREAD

**Issue by ACuteWoof** [zS1L3NT/ts-npm-ytmusic-api#3]
I use this API for my music app and it displays the year an album was released. On commit https://github.com/zS1L3NT/ts-npm-ytmusic-api/commit/e25f7e554697f2fd079214dfd04adc9d1a45b1df, this was removed from this API. I'd like you to bring it back.

**Comment by zS1L3NT** [comment]
Hi, this is possible but it has to be nullable. Not all albums on the YouTube Music website provide the year it was released. I'll release the new version shortly

**Comment by ACuteWoof** [comment]
Oh okay, thank you for your response. I'd be fine with you making it nullable than not providing the year at all. :)
