### ISSUE TITLE
[BUG]: Incorrect artist name in albums data.

### ISSUE THREAD

**Issue by Dajust** [zS1L3NT/ts-npm-ytmusic-api#31]
### Please describe the current behaviour of the code.

```js
albumId MPREb_Ulsj5v7BPir {
  type: 'ALBUM',
  albumId: 'MPREb_Ulsj5v7BPir',
  name: 'The Highlights (Deluxe)',
  playlistId: 'OLAK5uy_ltJ_KB-4-iIKU686bW8acPuhWaw1QB7J4',
  artist: { artistId: 'UClYV6hHlupm_S_ObS1W-DYw', name: 'Album' }, // here's the error
  year: 2024,
  ...
 }
 ``` 
 
When you use the `getAlbum` method, the artist name property in the album data returns the album release type (`Album`, `EP`, `Single`) instead of the name of the artist. This also affects the artist name of all the songs in the album.

### Please describe the expected behaviour of the code.

 The artist name property in album data should return the correct artist name not the release type.

### What are the steps to reproduce the error?

Call the `getAlbum` method with the album Id.

**Comment by zS1L3NT** [comment]
Version v5.2.2 has been released with this bug fixed
