### ISSUE TITLE
[FEATURE]: Include `albumBasic` data in the `getSong` API.

### ISSUE THREAD

**Issue by Dajust** [zS1L3NT/ts-npm-ytmusic-api#32]
### Is this feature request related to a problem? If so, please elaborate

No

### Tell me about the feature you are requesting!

Currently, the `getSong` api does not include much information about the album the song belongs to. It will be nice to have more information, the same way we have it on the `searchSong` API. The  result of the `searchSong` API includes the `albumBasic` data. If possible, let's also have the `albumBasic` data in the `getSong` API.

**Comment by zS1L3NT** [comment]
Hi, unfortunately the YouTube Music API internally does not provide any information about the album when requesting the information about one specific song... So I can't really do anything on my end regarding this
