### ISSUE TITLE
[BUG]: Invalid value "undefined" for header "X-YouTube-Client-Name"

### ISSUE THREAD

**Issue by soko7awen** [zS1L3NT/ts-npm-ytmusic-api#33]
### Please describe the current behaviour of the code.

Unable to run the example code. I received the error `TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "X-YouTube-Client-Name"`

### Please describe the expected behaviour of the code.

Code runs successfully.

### What are the steps to reproduce the error?

I just tried running the example code.

**Comment by zS1L3NT** [comment]
Do you want to try awaiting the `ytmusic.initialize()` function before calling all the other methods? The API needs to be initialized first.
