### ISSUE TITLE
[BUG]:  The `getAlbum` API  is broken. Missing album name, artist, and thumbnails.

### ISSUE THREAD

**Issue by Dajust** [zS1L3NT/ts-npm-ytmusic-api#34]
### Please describe the current behaviour of the code.

The `getAlbum` API no longer returns the album name, year, artist, and thumbnails.

Example

```js
getting album... MPREb_zkvlkWx0ytJ
{
  type: 'ALBUM',
  albumId: 'MPREb_zkvlkWx0ytJ',
  name: 'Other versions',
  playlistId: '',
  artist: { artistId: null, name: '' },
  year: null,
  thumbnails: [],
  songs: [
    {
      type: 'SONG',
      videoId: 'w8eFZoOcYKc',
      name: 'Dawn FM',
      artist: [Object],
      album: [Object],
      duration: null,
      thumbnails: []
    }
    ...
  ]
} 
```

Now we have 'Other versions' for the album names instead of the actual album names.

### Please describe the expected behaviour of the code.

The API should return the correct album data.

### What are the steps to reproduce the error?

Call the `getAlbum` API and observe the result.

**Comment by zS1L3NT** [comment]
Version v5.2.2 has been released with this bug fixed
