### ISSUE TITLE
[BUG]: (4.0.0) Package main and types field are invalid

### ISSUE THREAD

**Issue by PapiOphidian** [zS1L3NT/ts-npm-ytmusic-api#8]
### Please describe the current behaviour of the code.

The package still points to dist/index.js and dist/index.d.ts, but those files no longer exist.

### Please describe the expected behaviour of the code.

N.A.

### What are the steps to reproduce the error?

- import the module
- try to run it or compile it in typescript
- lol

### Additional Information

N.A.

**Comment by zS1L3NT** [comment]
Ohno, I'll fix it as soon as I get to my computer. Thanks for letting me know!

**Comment by zS1L3NT** [comment]
Version v4.0.1 has been released with the fix included

**Comment by PapiOphidian** [comment]
This fixes the issue. Thank you
